spring:
  application:
    name: category-service
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      fail-fast: false
      retry:
        useRandomPolicy: true
        initial-interval: 2000
        max-interval: 6000
        max-attempts: 5
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/
  instance:
    preferIpAddress: true
    hostname: localhost