services:
  kafka:
    image: confluentinc/confluent-local:7.4.3
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092" # for client connections
      - "9101:9101" # JMX
    restart: unless-stopped
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      CLUSTER_ID: 'K0EA9p0yEe6MkAAAAkKsEg'

  kafka-init-topics:
    image: confluentinc/confluent-local:7.4.3
    container_name: kafka-init-topics
    depends_on:
      - kafka
    command: "bash -c \
                'kafka-topics --create --topic telemetry.sensors.v1 \
                             --partitions 1 --replication-factor 1 --if-not-exists \
                             --bootstrap-server kafka:29092 && \
                kafka-topics --create --topic telemetry.snapshots.v1 \
                             --partitions 1 --replication-factor 1 --if-not-exists \
                             --bootstrap-server kafka:29092 && \
                kafka-topics --create --topic telemetry.hubs.v1 \
                             --partitions 1 --replication-factor 1 --if-not-exists \
                             --bootstrap-server kafka:29092'"
    init: true

  stats-db:
    image: postgres:16.1
    container_name: stats-service-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - stats_data:/var/lib/postgresql/data
    restart: on-failure

  discovery-server:
    build: infra/discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
    environment:
      - EUREKA_INSTANCE_HOSTNAME=discovery-server
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - app-network

  config-server:
    build: infra/config-server
    container_name: config-server
    ports:
      - "8888:8888"
    depends_on:
      discovery-server:
        condition: service_healthy
    environment:
      - SERVER_PORT=8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    healthcheck:
      test: >
        curl -f http://discovery-server:8761/eureka/apps/CONFIG-SERVER |
        grep -q "<status>UP</status>"
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 90s
    networks:
      - app-network

  gateway-server:
    build: infra/gateway-server
    container_name: gateway-server
    ports:
      - "8080:8080"
    depends_on:
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
    environment:
      - SERVER_PORT=8080
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_CLOUD_CONFIG_FAIL_FAST=false
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - app-network

  # ===================================================================
  # BUSINESS LOGIC SERVICES
  # ===================================================================
  collector:
    build: stats/collector
    container_name: collector
    ports:
      - "9091:9091"
    depends_on:
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
      kafka-init-topics:
        condition: service_completed_successfully
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - SERVER_PORT=9091
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9091/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - app-network

  aggregator:
    build: stats/aggregator
    container_name: aggregator
    depends_on:
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - SERVER_PORT=9092
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9092/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - app-network

  analyzer:
    build: stats/analyzer
    container_name: analyzer
    ports:
      - "9093:9093"
    depends_on:
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - SERVER_PORT=9093
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9093/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - app-network

  user-service:
    build:
      context: ./core/user-service
      dockerfile: Dockerfile
    container_name: user-service
    restart: unless-stopped
    ports:
      - "8081:8081"
    depends_on:
      stats-db:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SERVER_PORT=8081
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    healthcheck:
      test: >
        curl -s http://discovery-server:8761/eureka/apps/USER-SERVICE |
        grep -q "<status>UP</status>"
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - app-network

  category-service:
    build:
      context: ./core/category-service
      dockerfile: Dockerfile
    container_name: category-service
    restart: unless-stopped
    ports:
      - "8082:8082"
    depends_on:
      stats-db:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://category-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SERVER_PORT=8082
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SPRING_PROFILES_ACTIVE=docker
    healthcheck:
      test: >
        curl -s http://discovery-server:8761/eureka/apps/CATEGORY-SERVICE |
        grep -q "<status>UP</status>"
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - app-network

  event-service:
    build:
      context: ./core/event-service
      dockerfile: Dockerfile
    container_name: event-service
    restart: unless-stopped
    ports:
      - "8083:8083"
    depends_on:
      stats-db:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://event-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SERVER_PORT=8083
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    healthcheck:
      test: >
        curl -s http://discovery-server:8761/eureka/apps/EVENT-SERVICE |
        grep -q "<status>UP</status>"
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - app-network
  comment-service:
    build:
      context: ./core/comment-service
      dockerfile: Dockerfile
    container_name: comment-service
    restart: unless-stopped
    ports:
      - "8083:8083"
    depends_on:
      stats-db:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://event-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SERVER_PORT=8083
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    healthcheck:
      test: >
        curl -s http://discovery-server:8761/eureka/apps/COMMENT-SERVICE |
        grep -q "<status>UP</status>"
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - app-network
  request-service:
    build:
      context: ./core/request-service
      dockerfile: Dockerfile
    container_name: request-service
    restart: unless-stopped
    ports:
      - "8084:8084"
    depends_on:
      stats-db:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://request-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SERVER_PORT=8084
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    healthcheck:
      test: >
        curl -s http://discovery-server:8761/eureka/apps/REQUEST-SERVICE |
        grep -q "<status>UP</status>"
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - app-network
volumes:
  stats_data:
  ewm_data:
networks:
  app-network:
    driver: bridge