spring:
  application:
    name: gateway-server
  config:
    import: "configserver:"
  cloud:
    config:
      fail-fast: true
      retry:
        useRandomPolicy: true
        max-interval: 6000
      discovery:
        enabled: true
        serviceId: config-server
eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
    instance-id: "${spring.application.name}:${random.value}"
    leaseRenewalIntervalInSeconds: 10
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: DEBUG
    org.springframework.cloud.gateway.handler.FilteringWebHandler: DEBUG
    org.springframework.web.reactive.function.client: DEBUG