server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: admin-user
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**
          metadata:
            type: admin

        - id: admin-categories
          uri: lb://category-service
          predicates:
            - Path=/admin/categories/**
          metadata:
            type: admin

        - id: admin-compilations
          uri: lb://event-service
          predicates:
            - Path=/admin/compilations/**
          metadata:
            type: admin

        - id: admin-events
          uri: lb://event-service
          predicates:
            - Path=/admin/events/**
          metadata:
            type: admin

        - id: private-request
          uri: lb://request-service
          predicates:
            - Path=/users/*/requests/**
          metadata:
            type: private

        - id: private-request-event
          uri: lb://request-service
          predicates:
            - Path=/users/*/events/*/requests
          metadata:
            type: private

        - id: private-events
          uri: lb://event-service
          predicates:
            - Path=/users/*/events/**
          metadata:
            type: private

        - id: private-comment-create
          uri: lb://comment-service
          predicates:
            - Path=/*/events/*/comments
            - Method=POST
          filters:
            - StripPrefix=0
          metadata:
            type: private

        - id: private-comment-update-delete
          uri: lb://comment-service
          predicates:
            - Path=/*/comments/*
            - Method=PATCH,DELETE
          filters:
            - StripPrefix=0
          metadata:
            type: private

        - id: private-comment-search
          uri: lb://comment-service
          predicates:
            - Path=/*/comments/search
            - Method=GET
          filters:
            - StripPrefix=0
          metadata:
            type: private

        - id: public-events
          uri: lb://event-service
          predicates:
            - Path=/events/**
          metadata:
            type: public

        - id: public-categories
          uri: lb://category-service
          predicates:
            - Path=/categories/**
          metadata:
            type: public

        - id: public-compilations
          uri: lb://event-service
          predicates:
            - Path=/compilations/**
          metadata:
            type: public

        - id: public-comments-read
          uri: lb://comment-service
          predicates:
            - Path=/comments/**
            - Method=GET
          metadata:
            type: public

        - id: public-event-comments-read
          uri: lb://comment-service
          predicates:
            - Path=/*/comments
            - Method=GET
          metadata:
            type: public
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,env
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always
