server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: admin-api
          uri: lb://main-service
          predicates:
            - Path=/admin/**
          metadata:
            type: admin
        - id: private-api
          uri: lb://main-service
          predicates:
            - Path=/users/**
          metadata:
            type: private
        - id: public-events
          uri: lb://main-service
          predicates:
            - Path=/events/**
          metadata:
            type: public
        - id: public-categories
          uri: lb://main-service
          predicates:
            - Path=/categories/**
          metadata:
            type: public
        - id: public-compilations
          uri: lb://main-service
          predicates:
            - Path=/compilations/**
          metadata:
            type: public
        - id: public-comments
          uri: lb://main-service
          predicates:
            - Path=/comments/**
            - Path=/*/comments/**
          metadata:
            type: public
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,env
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always
