eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/
  instance:
    preferIpAddress: true
    hostname: localhost

logging:
  level:
    root: INFO
    ru.yandex.practicum.main: DEBUG
    org.springframework.web.servlet.mvc.method.annotation: TRACE
    org.springframework.web: DEBUG